django-admin startproject backend
python manage.py startapp api



python manage.py makemigrations
python manage.py migrate

python manage.py runserver

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1OTM3NzQxMywiaWF0IjoxNzU5MjkxMDEzLCJqdGkiOiIyZTVmZThjNWNlNmQ0NjkxOGZjZWE5Zjc5ODA0ZjAzMCIsInVzZXJfaWQiOiIxIn0.ZwF8JUzNGH-wlcKfykpA_4NWOqaZf3yBH34FCjQoCcw",
    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5MjkyODEzLCJpYXQiOjE3NTkyOTEwMTQsImp0aSI6IjI2M2M2YTllN2U4MjQ4NWZiMTUxNmEzNDkxM2QyNGM4IiwidXNlcl9pZCI6IjEifQ.Ryd6l9exQrZU6tjL7GBKeMNRkbP6lazAcgqZ12mKxI4"
}
{
    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5MjkyODk0LCJpYXQiOjE3NTkyOTEwOTQsImp0aSI6IjJhYTUzNTM2ZGIzYjQ2OWI5ZmEwOTU2OTE1OWM2YTZkIiwidXNlcl9pZCI6IjEifQ.hHCcrblNw0gs7PWpnTXZr1XjvX3Tn1rlmlLEWPXEbTg"
}
{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1OTM3OTA4NiwiaWF0IjoxNzU5MjkyNjg2LCJqdGkiOiI5OTQ5NjgwY2ViMGQ0Yzk0OTIwMDFmNTRhNWRiYmI4OCIsInVzZXJfaWQiOiIxIn0.AnYKcJCRgvBDVUiZ6NIfcOtCJtMHQX8mvncLcwLpqOw",
    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5Mjk0NDg2LCJpYXQiOjE3NTkyOTI2ODYsImp0aSI6IjAyNWYwNDY3YzFiZDQ2YmI5Y2M4Njc4MDZhZTFjM2UzIiwidXNlcl9pZCI6IjEifQ.ZvJ3xgN_KM4lUb1_sXcxIozhkXTZfqMFRglNEZpD1Zk"
}